---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-primevideo-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: amazon-primevideo
  template:
    metadata:
      labels:
        app: amazon-primevideo
    spec:
      containers:
      - name: amazon-primevideo-container
        image: vickey99/amazon-primevideo
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: amazon-primevideoservice
spec:
  type: LoadBalancer
  selector:
    app: amazon-primevideo
  ports:
  - port: 80
    targetPort: 3000
